version: '3.8'

services:
  balanzo_frontend:
    container_name: balanzo_frontend
    build:
      context: ..
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://localhost:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
